### ISSUE TITLE
Support changing media from MultiFunPlayer

### ISSUE THREAD

**Issue by OpenFunscripter** [Yoooi0/MultiFunPlayer#100]
Hi
I saw the plugin API you recently added and will definitely look into using it for a unnamed side project (not OFS related).

I haven't done much yet but I saw that using the `MediaPathChangeMessage` wouldn't load the video in mpv.
So I went and looked why that is.

It turned out to be trivial to add. OpenFunscripter@1873320883b8c7d44358253c94e6185dfd7c54a8 
I can create a pull request if you want.
Assuming there isn't anything catastrophically wrong with this.

Not sure if this is also possible with the other players.

**Comment by Yoooi0** [comment]
Yea there is no way currently to make video players load a video from MultiFunPlayer code.

The `MediaPathChangedMessage` is for the video players to inform MultiFunPlayer about a video change. 
And in case of plugins, it is one of the messages that allows them to act as a video player.
While it might work, the same message is also handled internally by MFP and it might cause problems in the future.

I had this planned anyways so I will add it soon. It basically just hast to be a separate message, and also handled by other supported video players.

**Comment by OpenFunscripter** [comment]
I understand.
Anyway love the plugin addition. 🙂

**Comment by Yoooi0** [comment]
Added as separate message.

> Anyway love the plugin addition. 🙂

👍 
Its probably not the best plugin system implementation but it will do for now.

**Comment by OpenFunscripter** [comment]
Thank you for adding this
