### ISSUE TITLE
Add stash-vr-companion as remote script library

### ISSUE THREAD

**Issue by Tweeticoats** [Yoooi0/MultiFunPlayer#103]
I develop stash-vr-companion and have implemented the deovr api and heresphere api in my application in a similar way to xbvr.
The deovr api works by fetching /devor and this provides a json list of scenes pointing to another json file with metadata about the scenes including a url to download a funscript file.
The heresphere provide a simiar api to get scene metadata and links to the funscript.

If you can add support for fetching matching and loading these funscripts from the api instead of requiring the user to download the scripts and loading them manually.

**Comment by Yoooi0** [comment]
I think you could write this as a MFP plugin:
https://github.com/Yoooi0/MultiFunPlayer/blob/master/MultiFunPlayer/Plugin/PluginBase.cs

Adding this to MFP would require some bigger internal changes.
I'll add an issue for support of script libraries like this, but for now I think it would be good plugin.

**Comment by Yoooi0** [comment]
Also iirc someone on eroscripts is making a MFP plugin with browser extension for stash

**Comment by Yoooi0** [comment]
I think I will close this for now, if anything I will add stash as funscript library using their official api, if not possible or too hard I will reopen this.
Maybe heresphere will also send scripts from /heresphere json api over remote control api in the future.

I would rather rely on official apis, other/smaller integrations would be better as a plugin.
