### ISSUE TITLE
Need help with Buttplug io and MFP interaction

### ISSUE THREAD

**Issue by MellowEdge** [Yoooi0/MultiFunPlayer#108]
I have connected MFP to MPV as input and Buttplug.io as output and I have a device connected to Buttplug.io, I loaded up the video and script and I see axis moving, but my device doesn't react. It reacts to [Buttplug Playground](https://playground.buttplug.world/) so I know it works, but I'm not sure what I'm missing here, do I have to set up axis manually?

Here's how my device looks in buttplug.io 
![image](https://user-images.githubusercontent.com/26963226/206767738-41664699-036b-4807-a1a8-a8156d83ba41.png)

**Comment by Yoooi0** [comment]
You have to expand device map under buttplug and map an axis to your device.

![2022-12-09_19-34-56](https://user-images.githubusercontent.com/63662834/206769570-cf908d91-5a27-44b8-b136-bca07a3d2c1e.png)

**Comment by MellowEdge** [comment]
Oh, I see, completely missed it. Now it works, thanks!
