### ISSUE TITLE
Serial disconnect results in a modal error dialog box

### ISSUE THREAD

**Issue by jonathonbarton** [Yoooi0/MultiFunPlayer#11]
As an MFP user, I use a microUSB cable with a magnetic tip to connect o a PC, and I use MFP with VR.
On occasion the cable has been pulled and it disconnects, and I reconnect it (since it's magnetic, that's easy to do by feel with an HMD over your eyes. It snaps into place with no problem
Alternately, I disconnect the cable and power from the connected device before closing the software.

In both cases, an error box pops up that requires a user action to close. With the new ability to auto-connect to interfaces that shouldn't happen anymore. If Serial comms (or others, including the various software apps) are lost, MFP should go into a silent reconnecting loop until either Serial is re-established or until the interface is stopped with the stop command (in the UI or with a keybind-equivalent)

**Step to reproduce**
1. Connect a serial device to MFP with a USB cable and play a video with a funscript.
2. unplug the USB cable from the serial device.
3. observe the error box with the OK button. 

**Desired behavior**
When the USB cable is disconnected, MFP should:
1. Return the device to the home position
2. Attempt to reconnect to the disconnected device or player software until the connection is re-established OR until the user manually stops the interface/software player with the UI or keybind equivalent.

**Comment by Yoooi0** [comment]
Yea I have also experienced this issue, for some reason the autoconnect thinks that it can connect without the serial port existing. The actual connection is the same as if you pressed the connect button manually in case there are other errors that need user attention, thats why it shows the dialog.

**Comment by Yoooi0** [comment]
Should be fixed in this build: https://github.com/Yoooi0/MultiFunPlayer/actions/runs/915744532
