### ISSUE TITLE
Serial connection stops sending t-code messages after a time

### ISSUE THREAD

**Issue by mnh86** [Yoooi0/MultiFunPlayer#116]
**Describe the issue**

Hello! I am using MultiFunPlayer with a t-code connection to a custom ESP32 device controller over serial USB. I can successfully run multi-channel funscripts, which is amazing. But there are times when I am using OpenFunscripter as a connected player for a while (like 20 mins), and then something hangs up in MFP and it stops sending t-code messages to my device. MFP displays the value changes from OFS in the UI, as well as the Serial device connected, but I’m not seeing data sent to the device (from the readout on the device itself).

I haven’t dug into where the issue might be happening yet, but curious if you had some ideas on how to triage (enable certain logs, different tests to try, etc.).

Also, It is difficult to replicate. And when it does, I haven’t figured out a surefire repeatable process to recover when the issue occurs. If I try disconnecting/reconnecting the Serial device manually several times in MFP, it seems to eventually work again. Some times it recovers more quickly than others.

I’ll keep an eye out if I notice anything else.

**Comment by Yoooi0** [comment]
You can enable trace logs and see if/what data is sent when that happens.
From your description its possibly just connection getting loose from vibrations and somehow not allowing data to be sent.
I think its more likely a driver/windows/connection issue than MFP issue.
