### ISSUE TITLE
Odd device, don't know how to connect

### ISSUE THREAD

**Issue by Smedbee** [Yoooi0/MultiFunPlayer#119]
I just posted a little bit ago as I'm learning how to use this app, so bear with me a little! I have a hismith machine, which can connect to Initface Central, which is what I'm using when I connect the player to "buttplug.io". I am able to connect the two apps together just fine, with my machine also connected to Initface. However, when I play scripts or try to connect my machine to the MultiFunPlayer, it doesn't work. I'm not sure if this is from the axis options, which I had configured all available ones, including creating my own axis to try and make it work. In Initface, it says it is "Oscilate", I'm guessing because of the motor turning? This has a Oscilation Speed Step Count that I can manually control (and does work) which should work with the player, but I can't get it to sync with my funscript I load in. Any help with this issue would be greatly appreciated!

**Comment by Yoooi0** [comment]
I think you need to use latest development build: https://github.com/Yoooi0/MultiFunPlayer/actions/runs/4265603709
It has an updated buttplug library that should support the hismith.

Also in MFP make sure to map your device to some axis in buttplug.io output settings.

**Comment by Yoooi0** [comment]
I'm assuming it works. Reply here if it doesn't.
