### ISSUE TITLE
TCP output sends data in 1024 byte chunks

### ISSUE THREAD

**Issue by diglet48** [Yoooi0/MultiFunPlayer#122]
Hi. I was running some tests with the TCP and UDP outputs. UDP works as expected, but MFP only seems to send TCP packets when they are full (1024 bytes payload in wireshark). This results in low update rate at the target device (around 1 packet per second).

I think I saw this working a few months ago.

**Comment by Yoooi0** [comment]
Looking at the code it looks like TCP never worked right, thanks for reporting.
Fixed build: https://github.com/Yoooi0/MultiFunPlayer/actions/runs/4579496637

**Comment by Yoooi0** [comment]
I'm assuming its fixed
