### ISSUE TITLE
Crash when attempting to add or remove new axis to cloned t-code device

### ISSUE THREAD

**Issue by Apollo1298** [Yoooi0/MultiFunPlayer#133]
**Describe the bug**
If applicable, add screenshots, logs or anything else that can help diagnose the bug.

**To Reproduce**
1.Settings>device
2. Clone T-code 0.2 or 0.3
3. Add or remove output
[latest.log](https://github.com/Yoooi0/MultiFunPlayer/files/12115928/latest.log)
Log attached

**Comment by Yoooi0** [comment]
I could not reproduce this.
Could you attach a new log but with log level set to "Trace" and "Enable UI logging" checked?

**Comment by Apollo1298** [comment]
[latest.log](https://github.com/Yoooi0/MultiFunPlayer/files/12126670/latest.log)
Done

**Comment by Yoooi0** [comment]
Fixed, thanks for reporting!
Will be in 1.26.1, in the meantime you can also download the build from [github actions](https://github.com/Yoooi0/MultiFunPlayer/actions).

**Comment by Apollo1298** [comment]
Yep that worked, thanks!
