### ISSUE TITLE
Can't connect Svakom Sam Neo to Intiface, tried 3 diff BT adapters

### ISSUE THREAD

**Issue by GordonHollow** [Yoooi0/MultiFunPlayer#137]
When i start searching it found device, connect and instantly disconnect, with this error in log

Device errored while trying to connect: Device type specific error: Btleplug error: Not connected

Latest Intiface 2.4.3, also try mobile app too with same result

It works fine on xtoys\app and site with BT adapters i have tho

**Comment by Yoooi0** [comment]
This sounds like intiface issue not MFP.
Change log level to trace and enable ui logging via the cog button on top of the window, then recreate the issue and post the latest log file.

**Comment by GordonHollow** [comment]
Their github link is broken and leads nowhere, so i post here
don't see this log things your talk, but here is more logs from Intiface
![изображение](https://github.com/Yoooi0/MultiFunPlayer/assets/23491996/d2b73142-b70d-4026-b2cc-2b9a6517679e)
