### ISSUE TITLE
Recursive Script Library Folders

### ISSUE THREAD

**Issue by katodevin** [Yoooi0/MultiFunPlayer#141]
Would love for the option for Script Libraries to allow for recursive handling of funscripts.  Desired functionality would be automatic loading of funscripts in subfolders of Script Libraries when associated media is loaded.

**Comment by Yoooi0** [comment]
Thats already a thing:
![tCbJrYBVtt](https://github.com/Yoooi0/MultiFunPlayer/assets/63662834/30e16ff2-15d4-4ae3-9bc7-8ad9b0b56127)
