### ISSUE TITLE
Spline Interpolation

### ISSUE THREAD

**Issue by feilong123** [Yoooi0/MultiFunPlayer#146]
Why not use spline interpolation, which will make the script smoother. At present, if I want to make the funscript smoother, I can only change the polyline of the script into an approximate curve.

**Comment by Yoooi0** [comment]
You need to expand on what you mean. 
PCHIP and makima are splines and are not approximate curves, they pass thru each control point.

**Comment by feilong123** [comment]
Thanks, I know it. makima is good.

**Comment by feilong123** [comment]
You can close this issue.
