### ISSUE TITLE
using proxy in VR like v2ray or clash, MFP can't  connect deovr

### ISSUE THREAD

**Issue by vvv100** [Yoooi0/MultiFunPlayer#154]
**Describe the bug**
when using proxy in vr 
![image](https://github.com/Yoooi0/MultiFunPlayer/assets/89778846/6c479ad3-9d11-4553-9e98-717083c14411)
when close proxy in vr 
![image](https://github.com/Yoooi0/MultiFunPlayer/assets/89778846/4e11bd4c-cc66-4aaa-bcf6-0ccddda79ba5)

I think this problem is kind of important, cuz some aisa country like china can't access to google or SLR

**Comment by Yoooi0** [comment]
I don't know what could be done in MFP to "fix" this. There is nothing to be done if it can't access the IP on local network. This is more of a firewall/networking issue. I'm assuming you are running the proxy on your quest, it probably blocks all lan traffic and routes everything thru a tunnel. You need to make it to allow access to lan.

**Comment by Yoooi0** [comment]
Closing, if you think this is actually a bug comment here and I'll reopen.
