### ISSUE TITLE
Support sending API key to Stash

### ISSUE THREAD

**Issue by itsame-luigi** [Yoooi0/MultiFunPlayer#162]
**Describe the solution you'd like**
MultiFunPlayer cannot use Stash as a script repository when Stash has been configured to use a username/password. When configured in this way, connections to Stash's graphql endpoint require either an `ApiKey` header or an `apikey` query parameter.

Related: #117

**Comment by Yoooi0** [comment]
Added: https://github.com/Yoooi0/MultiFunPlayer/actions/runs/8840721452
Let me know if it works.

**Comment by itsame-luigi** [comment]
That works, thanks!
