### ISSUE TITLE
Media path modifier question for replacing %20 to space for Kodi DLNA

### ISSUE THREAD

**Issue by archborns** [Yoooi0/MultiFunPlayer#163]
I'm using Kodi DLNA and troubled playing funscript with video file with spaces.

Original video name: Video Name.mp4
Original funscript name: Video Name.funscript

MultiFunScript detected the file name as: Video%20Name.mp4

I tried creating Media Path Modifiers with Match Case checked, Find=%20, and Replace= (space)
However the MultiFunScript still detected the file name as: Video%20Name.mp4

What did I do wrong and how can I fix this?

Thanks in advance.

**Comment by Yoooi0** [comment]
What video player are you using?

Before connecting to video player can you change log level to trace via application settings at the top of the window, then connect and try playing a video with spaces, then check log level back to info and send me the `latest.log` file from the `Logs` folder.

**Comment by archborns** [comment]
Apologize I forgot to mention that I was using DeoVR over DLNA on Pico 4.

Using DeoVR over DLNA, the player seems unable to find script named with "NSN%20EP%2023.funscript" since actual script is "NSN 20EP 2023.funscript"
2024-04-29 06:55:11.7523|INFO|MultiFunPlayer.Script.Repository.ViewModels.ScriptRepositoryManager|Trying to match scripts to resource [Name: NSN%20EP%2023.mp4, Source: http://192.168.20.8:1160/%/61ad72b43c78c0f22d4d370b18888756]

Using MPC-HC locally working fine:
2024-04-29 06:56:07.6583|INFO|MultiFunPlayer.Script.Repository.ViewModels.ScriptRepositoryManager|Trying to match scripts to resource [Name: NSN EP 23.mp4, Source: F:\AV\FUNVID\FUN-Uncategorized]
2024-04-29 06:56:07.6743|INFO|MultiFunPlayer.Script.Repository.ViewModels.ScriptRepositoryManager|Matched L0 script to "NSN EP 23.funscript"

[latest.log](https://github.com/Yoooi0/MultiFunPlayer/files/15144257/latest.log)

**Comment by Yoooi0** [comment]
Your url from DLNA server is double encoded. Modifiers work on the raw received data and the `%20` is not present there:
`http://192.168.20.8:1160/%25/61ad72b43c78c0f22d4d370b18888756/NSN%2520EP%252023.mp4`
Instead try adding find: `%25` replace: `%`. Then the `%20` will get decoded by MFP like with MPC-HC.

**Comment by archborns** [comment]
I tried to set the MPM to find: %25 and replace: %.
Tthe MFP did showing correct file name NSN EP 23.mp4 instead of NSN%20EP%2023.mp4 now, however weirdly the script was not matched.

[latest.log](https://github.com/Yoooi0/MultiFunPlayer/files/15144711/latest.log)

**Comment by Yoooi0** [comment]
You have 2 script libraries added, is the `NSN EP 23.funscript` in either `F:\AV\FUNSCRIPT` or `E:\AV\FUNSCRIPT`?

**Comment by archborns** [comment]
I did forget to move the NSN EP 23.funscript to the script libraries, It was still on the same folder as the media / NSN EP 23.mp4.
By playing over DLNA, MFP cannot read the local funscript.  Thats explain why even the MFP did showing the correct file name after configured the MPM find: %25 and replace: %, the script was not loaded / matched.

After set the MPM to find: %25 and replace: % and moved the `NSN EP 23.funscript` to one of the script libraries folder, the script match / loaded just fine.

Appreciate for your kind support!
