### ISSUE TITLE
Some settings not saving when set to null

### ISSUE THREAD

**Issue by hidden2u** [Yoooi0/MultiFunPlayer#166]
When Motion Provider is selected, any changes are successfully saved in config file and restored at program start.  However if motion provider is deselected via the "x" button, that is not saved in the config.  i.e. there will always be a Motion Provider active for an axis once it is initially selected.

Tested on clean install with v1.29.4

**Comment by Yoooi0** [comment]
Thanks for reporting, fixed, will be in v1.30.0
