### ISSUE TITLE
Gap Fill not working with PolledUpdate

### ISSUE THREAD

**Issue by lynceus666** [Yoooi0/MultiFunPlayer#173]
**Describe the issue**
The gap fill option (e.g. using a looping script whenever there is a gap in the current script) works fine as long as the update setting in Device Map is set to FixedUpdate.
But when the update setting is set to PolledUpdate, the looping script set in the motion setting is ignored.

**Expected behavior**
If there is a looping script set in the motion setting (e.g. MotionProvider= LoopingScript, Script="RandomPattern.funscript") and the current script played via Buttplug.io has a gap larger than the gap defined in the gap fill setting, the looping script should fill the gap. This currently only works if the Update Setting under Device Map is set to FixedUpdate.

**Comment by Yoooi0** [comment]
When using PolledUpdate only script actions are sent, all other MFP features are ignored.
Technically using LoopingScript motion provider you are also playing a script, so it should be possible, but im not sure how it would work with all the "update when" options as the motion provider could stop updating in between two actions.
PolledUpdate was added only for devices that cant handle higher update rates, so they at least can play a script.
