### ISSUE TITLE
SpeedLimitSecondsPerUnit and SpeedLimitUnitsPersSecond offset shortcuts do not function as expected

### ISSUE THREAD

**Issue by jbooblesmith** [Yoooi0/MultiFunPlayer#186]
**Description**
---
**Expected behavior:**
-  I should be to set negative values to decrease the speed limit in either units per second or seconds per unit.
-  Positive offset values for units per second should decrease seconds per unit and vice/versa

**Actual behavior**
- Negative values are rounded up to zero when set.
- Positive offset values for seconds per unit increase units per second.

**To Reproduce**
---
**Negative values are rounded up to zero when set:**
1. Open shortcut settings
2. Add button click shortcut
3. Record any gesture
4. Set action to `Axis::SpeedLimitSecondsPerUnit::Offset` or `Axis::SpeedLimitUnitsPerSecond::Offset`
5. Attempt to set negative value
6. Value will be rounded up to zero

**Positive offset values for seconds per unit increase units per second:**
1. Open shortcut settings
2. Add button click shortcut
3. Record any gesture
4. Set action to `Axis::SpeedLimitSecondsPerUnit::Offset`
5. Set any positive value
6. Close shortcut settings
7. Trigger recorded gesture
8. UnitsPerSecond will increase while SecondsPerUnit decreases

**Comment by Yoooi0** [comment]
Thanks for reporting.
Fixed both bugs internally, will be in v1.31.1 or v1.32.0.
