### ISSUE TITLE
Something in 1.30.0 breaks autodetection of local scripts when using Emby

### ISSUE THREAD

**Issue by DJGoo** [Yoooi0/MultiFunPlayer#187]
**Describe the issue**
In all the versions after and including 1.30.0 I cannot get multifunplayer to detect local funscripts when using emby. 
I tried both the emby theatre, the webui, and vlc on each version from 1.29.4 and on all the 1.30.* releases emby would connect but wouldnt detect anything. other players like vlc seem totally unaffected, and all the other aspects seem fine.

**Expected behavior**
In 1.29.4 as long as the funscript files are correctly named and located multifunplayer loads them correctly for emby no different than vlc 
 or any other player.

PS: thanks for all your work.

**Comment by Yoooi0** [comment]
Yes, I broke Emby and Jellyfin by accident when cleaning up the code: https://github.com/Yoooi0/MultiFunPlayer/commit/b7c307bf0ae033cc16617385070ae046fbd01ae8

Apparently you have to specify that the attribute is to be applied to the property:
`[property: JsonProperty("ReportedDeviceId")]`
which I didnt know so it reads invalid device id in v1.30.0.

Fixed internally, will be in v1.31.1 or v1.32.0
