### ISSUE TITLE
Plugin settings are only saved after the plugin finishes executing

### ISSUE THREAD

**Issue by jaynopsis** [Yoooi0/MultiFunPlayer#188]
Currently, saving is only called when the script execution is ended. This is a bit confusing, could you please add a save every time the settings window is closed?

**Comment by jaynopsis** [comment]
Yeah, I'm using this. Gui is rendered correctly. I'm talking about cases when settings are edited without starting plugin (before starting or after stopping). Settings are visually updated, but they are not saved to disk:

1. Open the settings
2. Change something
3. Close settings
4. Close the player


In this case nothing will be saved to disk (but you can open the settings window as many times as you like while app is running). To save it, you need to start and stop the plugin before closing the player.


If this is the way it's designed, okay. I'll just add a note to the plugin instructions to start and stop it for save settings

**Comment by Yoooi0** [comment]
Hmm yea looking at it now it does indeed work very weirdly. 
It looks like you can only change settings after starting the plugin, otherwise they get overwritten from disk.
I'll change this to make more sense, thanks for bringing this up.
