### ISSUE TITLE
Deleting video directory outside of program causes it to be unable to start up to resolve

### ISSUE THREAD

**Issue by digiholic** [Yoooi0/MultiFunPlayer#19]
If a video directory is chose and is unavailable (for example, being on an external disk), the program will fail to launch providing the attached error stack trace.

Steps to reproduce:
1. Boot up MultiFunPlayer and choose a directory for the "videos" library folder
2. Close MultiFunPlayer
3. Delete, rename, or move the directory chosen
4. Attempt to boot the program again.

[log.20210808.0.log](https://github.com/Yoooi0/MultiFunPlayer/files/6952039/log.20210808.0.log)

**Comment by Yoooi0** [comment]
Thanks for the bug report.
Try this build: https://github.com/Yoooi0/MultiFunPlayer/actions/runs/1113157442
