### ISSUE TITLE
SR6 auto home off center

### ISSUE THREAD

**Issue by dizzyflames** [Yoooi0/MultiFunPlayer#193]
**Describe the issue**
Plugged the SR6 in and as soon as its connected to the app, it auto homes off to the far right. This causes some very erratic movements as the SR6 is jerking around a lot left and right.

**Expected behavior**
The auto homing is fine when I use MOSA so seems like its an issue with the player. Am I supposed to change the settings for the SR6?

[latest.log](https://github.com/user-attachments/files/18225848/latest.log)

**Comment by Yoooi0** [comment]
Thats not an issue with MFP, its an issue with esp32 or the firmware, its a known issue that was reported many times.
To the right of com port there are advanced settings, you can try disabling dtr and rts.
You can also switch from serial to udp and you wont get this issue.
