### ISSUE TITLE
Incorrect media name when using DeoVR and DLNA

### ISSUE THREAD

**Issue by WilliamBakersGithub** [Yoooi0/MultiFunPlayer#194]
When using DeoVR and streaming video via DLNA from PC, the file name received by the player is incorrect, seems to be just a random string, so the script can't be loaded automatically.
<img width="270" alt="MultiFunPlayer_2024-12-27_18-26-02" src="https://github.com/user-attachments/assets/c59b6dc6-782f-4bfa-a6cf-c5637a9f0086" />

**Comment by Yoooi0** [comment]
DLNA servers always have random names, there is nothing DeoVR or MFP can do about that.
