### ISSUE TITLE
Suggestion: Add ability to enable/disable sync

### ISSUE THREAD

**Issue by Skell67** [Yoooi0/MultiFunPlayer#2]
a loop function for short videos would be cool

**Comment by Yoooi0** [comment]
Sorry for late reply.

All of the supported players should have a loop function built in so it should work fine in MultiFunPlayer.
Unless I misunderstood your suggestion or there is an issue/bug in MultiFunPlayer.

**Comment by Skell67** [comment]
what I meant was that as soon as the video loop the OSR stops and starts again with a smooth transition

**Comment by Yoooi0** [comment]
There is no way to know if the video is looping, they players just change the time to the beginning of the loop and MFP detects it as a user seek so it starts the sync process to prevent jerky motion.

What I could do is add options to the sync so you can toggle it on/off.

**Comment by Skell67** [comment]
if it's possible and you don't mind adding this option it could be nice.

Thank you for answering my problem ^^

**Comment by Yoooi0** [comment]
Try this build: https://github.com/Yoooi0/MultiFunPlayer/actions/runs/578816696

Added sync settings that can be accessed by pressing the sync icon (near play/pause icon).

**Comment by Skell67** [comment]
oh thanks you made it fast  :), I'll test it tomorrow

**Comment by Yoooi0** [comment]
Did you manage to test it? I would like to close this issue if you did not have any problems.

**Comment by Skell67** [comment]
Sorry for the late answer, yes it works perfectly. Thank you.
