### ISSUE TITLE
Vibrations often don't stop

### ISSUE THREAD

**Issue by FreakyHD** [Yoooi0/MultiFunPlayer#20]
Sometimes the vibrations don't stop, even when the V0 axis is 0
The device itself keeps vibrating? Changing the update rate from 60hz to 0 and back to 60hz makes the device stop vibrating.

**Comment by Yoooi0** [comment]
Check this build: https://github.com/Yoooi0/MultiFunPlayer/actions/runs/1251208341

I only found one bug that could sometimes prevent vibrations from stopping, but that would still be very rare.
Also not sure how you made the update slider fix this issue, it just changes the idle time between updates.

**Comment by FreakyHD** [comment]
The issue looks fixed. I will re-open if I encounter this issue again.
