### ISSUE TITLE
"Update when Paused" seems like it's always active, even when disabled

### ISSUE THREAD

**Issue by barrettj** [Yoooi0/MultiFunPlayer#36]
Release v1.17.2.0

If I setup motion and turn on "Update without Script" it will immediately start moving that axis, regardless of video player status and regardless if "Update when Paused" is checked.

Notice how in the screenshots the axis has moved even though the video is paused and "Update when Paused" is not enabled

![Screenshot 2021-12-09 173924](https://user-images.githubusercontent.com/361635/145492700-427d55d5-ea9c-44ac-a257-55562fda4a1e.png)
![Screenshot 2021-12-09 173950](https://user-images.githubusercontent.com/361635/145492702-2e330284-2e21-4d8d-9206-6dd08d26dc0f.png)

**Comment by barrettj** [comment]
I would appreciate it there was at least an option for And - as is when I pause the video there's still motion which is undesirable for me

Or maybe I'm having some other issue (or misunderstanding) - there are a LOT of settings.  

I have to have "Update without script" on for the motion provider to do anything at all (since none of my videos have scripts for the axis I want to add motion providers to)

**Comment by Yoooi0** [comment]
Yea now that I think about it the current behavior makes no sense. 
You cant have random motion on non scripted axis be paused with video, which is what you want.
I'll rework that part to be more usable.

**Comment by Yoooi0** [comment]
Should be fixed in this build: https://github.com/Yoooi0/MultiFunPlayer/actions/runs/1584464122

**Comment by barrettj** [comment]
Can confirm - thanks!

I also really like the bypass color change - Smart Limit (and maybe invert) might benefit from a more differentiated on/off state as well
