### ISSUE TITLE
Suggestion: Implement workaround for axis jerk

### ISSUE THREAD

**Issue by barrettj** [Yoooi0/MultiFunPlayer#37]
There's currently a bug in the firmware where there will be random jerk added to the last axis because a character is dropped: https://discordapp.com/channels/664171761415356426/664173666963030016/916778835826077696

I usually experience the jerk on R2 (which is a mild inconvenience) but when it happens on R0 it can unplug the TValve.  I'm assuming MFP only sends axis values when they change which is why sometimes it's my R2 that jerks and sometimes my R0.

A workaround that seems to work for me with the latest version (since I don't use vibes or V0) is to set V0 to a Random Motion that always goes and to crank the speed up.  When I do this I haven't seen it jerk any of the axis unexpectedly.  I believe what's happening is now it's always sending a V0 axis command every single update where as before the last axis on any command sent could vary and then cause a random axis to jerk.

Tempest is sending A90 at the end of every command in his serial controller, if I'm understanding correctly

**Comment by Yoooi0** [comment]
I think your workaround is valid, no need to add special code just to handle this imo.
It will be fixed eventually.

> I'm assuming MFP only sends axis values when they change which is why sometimes it's my R2 that jerks and sometimes my R0.

Yes, that in itself was a fix for SR6 romeo firmware which could handle that many commands at once.
MFP used to send all axes at the same time.

**Comment by barrettj** [comment]
It may be worthwhile to add a fix (perhaps only if the user is using SR6 axis as the current SR6 plans are for the ESP32).

I can't be the only one that re-did their wiring several times searching for a grounding fault and I personally also ordered a second parallax servo thinking it was bugging out before I realized it was a software issue.  

MFP was/is my go to test app and I never experienced the issue on my OSR2+ so it took me longer than it should have to realize it's a software issue (and wouldn't happen when I would send simple commands via serial).

**Comment by Yoooi0** [comment]
Saw your fork so I will close this.
