### ISSUE TITLE
Process name variants (Whirligig and DeoVR)

### ISSUE THREAD

**Issue by DUZszyi** [Yoooi0/MultiFunPlayer#44]
I am running one of the earlier free, as in not from steam, versions of whirligig. THis version is no longer available from the website it seems.

On https://github.com/Yoooi0/MultiFunPlayer/blob/be7b2d0a7736853c9eb4fba65bd528b17aea9c30/MultiFunPlayer/VideoSource/ViewModels/WhirligigVideoSourceViewModel.cs#L46 the a process with the name `Whirligig` is queried, however the version I am using has the name `Whirligig64bit`.

Currently I have no C# toolchain set up so I did not patch this name, instead I changed the application from `Whirligig64bit.exe` to `Whirligig.exe` and apparently unity then also expects `Whirligig_Data` folder instead of `Whirligig64_Data`. After this change MultiFunPlayer was able to find the process.

I don't know about the steam version, but in anycase checking for either `Whirligig` or `Whirligig64bit` instead of only the first one would solve this issue. I can make a PR if you want me too, but as I don't have a C# toolchain I would make it a "blind" one ;)

On a very similar topic I have a variant of `DeoVR` called `SLR`, from sexlikereal and as I understand this is a modified version of `DeoVR` with some integration with their online video portal. Would it make sense to `Process.GetProcessesByName` for either `DeoVR` or `SLR`? I haven't tried yet, but I'll do the same filename rename switcheroo from `SLR` to `DeoVR` to test.

**Comment by Yoooi0** [comment]
Good point, I wonder if its just better to remove that check and let it fail while connecting.

**Comment by DUZszyi** [comment]
Yes I think you can just remove the check, since the process is not used in any other way. The next exception that is shown is `System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.` which should also be good enough I think. For me at least it will.

I just tested with the SLR app, and it did not like the rename, so I created some skeleton app that just sleeps forever with the name `SLR.exe` to bypass the check. Connecting worked like a charm after I went on the SLR app into developer settings and enabled remote control.

**Comment by Yoooi0** [comment]
Try this build: https://github.com/Yoooi0/MultiFunPlayer/actions/runs/1752616376

Couldn't remove the check completely since HereSphere and DeoVR are implemented exactly the same in case they differ in the future. With auto-connect enabled on both it could for example say that it connected to DeoVR instead of HereSphere.

**Comment by DUZszyi** [comment]
Fantastic, working as expected:

 1. `Whirligig64bit.exe` autoconnects.
 1. `Whirligig.exe` autoconnects.
 1. `SLR.exe` autoconnects.

I don't have a DeoVR to test with, but looking at the patch I see no reason why it should not work.

Thanks for the quick fix and thanks for the `MultiFunPlayer` in general!
