### ISSUE TITLE
Error when trying to add buttplug.io device

### ISSUE THREAD

**Issue by soundchaser128** [Yoooi0/MultiFunPlayer#57]
**Describe the bug**

Hiya, I tried syncing a buttplug.io device (Lovense Gush) with a video, but it crashes when I actually try to add the device. I use version 1.20.0. 

I uploaded the log at this [gist](https://gist.github.com/soundchaser128/07c6eaef886fa85c5880203c6509a209)

**To Reproduce**
1. Open Intiface Desktop
1. Open MPV, open the video file
2. Start MultiFunPlayer
3. Load the script file into the V0 channel
4. Add a buttplug.io output and connect to it
5. Expand the device map section, select the V0 channel, the only connected device, VibrateCmd and index 0 (I'm not entirely sure what those do, but they were the only options)
6. Click the plus icon right to the row
7. App crashes

**Comment by Yoooi0** [comment]
Should be fixed in this build: https://github.com/Yoooi0/MultiFunPlayer/actions/runs/2005119920

**Comment by soundchaser128** [comment]
Thanks for the quick reply, I'm gonna give that a shot!

**Comment by soundchaser128** [comment]
Yep, that worked. Thanks!
