### ISSUE TITLE
Editable Presets for axes

### ISSUE THREAD

**Issue by dvojas** [Yoooi0/MultiFunPlayer#58]
I really enjoy the possibility to add motions to axes or link them to other axis. The thing is that for different part of script there are different settings I like and switching them on the go is a sollution, but when there are many settings (like link to L0+invert+add random motion) for multiple axes it is a lot to do. Something like save current settings to a Preset would be nice and then just load the presets. Maybe even some keystroke to go for next preset would be nice.

**Comment by Yoooi0** [comment]
Duplicate of #15
You can replicate presets with shortcuts, just add multiple actions per gesture that change what you want.

**Comment by dvojas** [comment]
That works
