### ISSUE TITLE
COM port stream freezes when playing video with fast moves, or when axis limits are changed quckly

### ISSUE THREAD

**Issue by StyleMavin** [Yoooi0/MultiFunPlayer#76]
While playing a VR video on DeoVR using Quest2, the app would cause my SR6 to freeze up, usually when a fast section happened or if I adjusted the L0 output limits quickly. Also, it would take several attempts of connect/disconnect to get all the axes to respond to commands, so that the SR6 moved as the script + motion providers were commanding. I tested after each connection by adjusting the L0, then the R0, the the R1 and R2 output limits to see if all axes responded. Many times, only L0 would respond, but then after another attempt, L0, R0 and L1 and L2 would respond, but R1 and R2 would not move. Then if I got them all moving, I could play a scene for a few minutes until the SR6 just froze. It would also freeze if I changed the output range limit on L0 very fast using an XBox  controller connected via Bluetooth. Finally after a few rounds of unplugging and plugging in the SR6, and reconnecting, MFP would crash.

**To Reproduce**
1. Connect to an SR6 via USB to your computer
2. Lauch MFP and set Motion Providers on R0 random, R1 random, R2 random + linked to L0
3. Connect via Serial port to the SR6
4. Verify that all the axes are responding to changes in their output limits
5. Load a video on Quest 2 in DeoVR
6. Load a script in MFP once DeoVR is connected to MFP
7. Play the video in DeoVR, find a fast section
8. Adjust the L0 output limits via the Xbox controller using the thumbstick to drive the changes quickly

[log.20220718.173.log](https://github.com/Yoooi0/MultiFunPlayer/files/9136267/log.20220718.173.log)

**Comment by Yoooi0** [comment]
Im not sure that is MFP issue, sounds more like the board/firmware issue. I've been using MFP from the start and never had that problem. Would also need a log file with MFP crashing. 
Btw your log level is set to Trace so it spams a lot of information that is unnecessary.
